use_default_settings: true

server:
  limiter: false
  image_proxy: true
  port: 8080
  bind_address: "0.0.0.0"

ui:
  static_use_hash: true

search:
  safe_search: 0
  default_lang: ""
  autocomplete: "google"
  favicon_resolver: "google"
  formats:
    - html
    - json
