services:
  queryly:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - searxng
      - redis
    volumes:
      - ./data:/data:rw
    env_file:
      - .env
    environment:
      - SEARXNG_API=http://searxng:8080
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "4321:4321"

  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    volumes:
      - ./configs/searxng/settings.yml:/etc/searxng/settings.yml:ro
    env_file:
      - .env
    environment:
      - UWSGI_WORKERS=2
      - SEARXNG_SECRET=${SECRET}
    labels:
      - com.centurylinklabs.watchtower.scope=third_party

  redis:
    image: valkey/valkey:8-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    environment:
      - VALKEY_EXTRA_FLAGS=--save 60 1 --loglevel warning
    labels:
      - com.centurylinklabs.watchtower.scope=third_party

  watchtower:
    image: ghcr.io/containrrr/watchtower
    restart: unless-stopped
    command: --cleanup --scope third_party --interval 900 --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis-data:
