services:
  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - UWSGI_WORKERS=2
    volumes:
      - ./configs/searxng/settings.yml:/etc/searxng/settings.yml:ro
