services:
  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - UWSGI_WORKERS=2
      - SEARXNG_SECRET=${SECRET}
    volumes:
      - ./configs/searxng/settings.yml:/etc/searxng/settings.yml:ro

  redis:
    image: valkey/valkey:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
